version: '3.7'

services:

  library:
    container_name: library
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - 3001:3000
    volumes:
      - .:/var/www/html/
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true